name: Deploy

on:
  push:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.11
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "desolate-sands-20483"
          heroku_email: "jennjenn93@gmail.com"

          21226ba2-09f5-433e-96c0-b7657038e2a7